### ISSUE TITLE
Docker images doesn't work

### ISSUE THREAD

**Issue by HoracceFeng** [yangxue0827/FPN_Tensorflow#1]
Hi, just wanna tell you that your docker images is for python3 tensorflow but not python2. You can check it by using "pip  show tensorflow", then you will find that actually your tensorflow are installed under py35. 

I only have py2_tensor1.1 and py3_tensor1.3 images, I will really appreciate it if you can re-upload the docker images. I tried using py3 but get error in many funcs -- not work ... Then I decide to change the code in py2_tensor1.1, and get error from "tf.cond()", even I change the "true/false_fn" to "fn1/fn2". It says that the variable "target_shortside_len" doesn't have variable name, like the following shows:

=============================================================================
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    train()
  File "train.py", line 34, in train
    is_training=True)
  File "../data/io/read_tfrecord.py", line 81, in next_batch
    is_training=is_training)
  File "../data/io/read_tfrecord.py", line 56, in read_and_prepocess_single_img
    target_shortside_len=shortside_len)
  File "../data/io/image_preprocess.py", line 27, in short_side_resize
    fn2=lambda: (target_shortside_len * h//w,  target_shortside_len))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1741, in cond
    orig_res, res_t = context_t.BuildCondBranch(fn1)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1668, in BuildCondBranch
    real_v = self._ProcessOutputTensor(v)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 1626, in _ProcessOutputTensor
    if val.name not in self._values:
AttributeError: 'int' object has no attribute 'name'
=============================================================================

Thank you so much!

**Comment by yangxue0827** [comment]
In fact, my code supports python3 and you can use the pytho3 command at run time.

**Comment by xiaoruiruia** [comment]
Do you solve this problem?

**Comment by HoracceFeng** [comment]
Sorry but ... nope, I finally change to another structure. Not sure if this will work but from my perspective, the version of tensorflow and python should be the most crucial one.

**Comment by xiaoruiruia** [comment]
我怀疑是构建tfrecord或者是读取tfrecord的问题
