### ISSUE TITLE
Strange questions, have anyone ever met ?

### ISSUE THREAD

**Issue by niuniu111** [yangxue0827/FPN_Tensorflow#16]
2018-05-25 22:02:57: step901    image_name:b'in000038.jpg' |	
                                rpn_loc_loss:0.4218079447746277 |	 rpn_cla_loss:0.11451516300439835 |	 rpn_total_loss:0.5363231301307678 |
                                fast_rcnn_loc_loss:0.0 |	 fast_rcnn_cla_loss:0.09883365035057068 |	 fast_rcnn_total_loss:0.09883365035057068 |
                                total_loss:1.065047264099121 |	 pre_cost_time:50.461886167526245s
Traceback (most recent call last):
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1139, in _do_call
    return fn(*args)
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 1121, in _run_fn
    status, run_metadata)
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Program Files\Anaconda2\envs\tensorflow\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.UnknownError: OverflowError: Python int too large to convert to C long
	 [[Node: fast_rcnn_loss/PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_7", _device="/job:localhost/replica:0/task:0/cpu:0"](fast_rcnn_loss/Squeeze_1, fast_rcnn_loss/mul_1, fast_rcnn_loss/strided_slice_1)]]

**Comment by chaojixiaohaizei** [comment]
您好，层主，请问您找到原因了吗？@niuniu111

**Comment by leiyaohui** [comment]
@niuniu111  @chaojixiaohaizei chaojixiaohaizei 你好，找到原因了吗？我遇到了同样的问题

**Comment by chaojixiaohaizei** [comment]
没有解决



---Original---
