### ISSUE TITLE
SIGNED INTEGER IS LESS THAN MINIMUM

### ISSUE THREAD

**Issue by Yinruihao** [yangxue0827/FPN_Tensorflow#18]
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    train()
  File "train.py", line 211, in train
    summary_str = sess.run(summary_op)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.OverflowError: signed integer is less than minimum
	 [[Node: draw_proposals/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_4", _device="/job:localhost/replica:0/task:0/cpu:0"](draw_proposals/Squeeze/_2597, draw_proposals/Gather/_2599, draw_proposals/strided_slice/_2601)]]
	 [[Node: fast_rcnn_loss/fast_rcnn_minibatch/RandomShuffle_2/_2483 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3787_fast_rcnn_loss/fast_rcnn_minibatch/RandomShuffle_2", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'draw_proposals/PyFunc', defined at:
  File "train.py", line 229, in <module>
    train()
  File "train.py", line 87, in train
    text=tf.shape(rpn_object_boxes)[0])
  File "../libs/box_utils/show_box_in_tensor.py", line 63, in draw_box_with_color
    Tout=[tf.uint8])
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 203, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 36, in _py_func
    name=name)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): exceptions.OverflowError: signed integer is less than minimum
	 [[Node: draw_proposals/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_4", _device="/job:localhost/replica:0/task:0/cpu:0"](draw_proposals/Squeeze/_2597, draw_proposals/Gather/_2599, draw_proposals/strided_slice/_2601)]]
	 [[Node: fast_rcnn_loss/fast_rcnn_minibatch/RandomShuffle_2/_2483 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_3787_fast_rcnn_loss/fast_rcnn_minibatch/RandomShuffle_2", tensor_type=DT_INT64, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

It seems that there is a problem of the summary_op part

**Comment by niuniu111** [comment]
I also met this mistake, have you solved it?

**Comment by EchoChung6** [comment]
Same problem here. 
And the problem cannot be reproduced, say, it occurs at step 100, but next time occurs at step 2000.

May we know the solution to this issue?
Many thanks.

**Comment by pyupcgithub** [comment]
@Yinruihao @niuniu111 @EchoChung6 @yangxue0827 
how to solve this problem?
I find although it was labeled duplicated, but there is no solution .

**Comment by Yinruihao** [comment]
> @Yinruihao @niuniu111 @EchoChung6 @yangxue0827
> how to solve this problem?
> I find although it was labeled duplicated, but there is no solution .

我已经放弃了这个程序了。建议你也换个别的。
