### ISSUE TITLE
楼主求助，这个错误是为什么啊

### ISSUE THREAD

**Issue by Yinruihao** [yangxue0827/FPN_Tensorflow#19]
Traceback (most recent call last):
  File "train.py", line 229, in <module>
    train()
  File "train.py", line 211, in train
    summary_str = sess.run(summary_op)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.KeyError: 2
	 [[Node: draw_boxes_with_categories/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT64, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_8", _device="/job:localhost/replica:0/task:0/cpu:0"](draw_boxes_with_categories/Squeeze/_2703, fast_rcnn_predict/fast_rcnn_proposals/Gather_6/_2705, fast_rcnn_predict/fast_rcnn_proposals/Gather_8, fast_rcnn_predict/fast_rcnn_proposals/Gather_7/_2707)]]
	 [[Node: draw_boxes_with_categories/Reshape/tensor/_2709 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4969_draw_boxes_with_categories/Reshape/tensor", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'draw_boxes_with_categories/PyFunc', defined at:
  File "train.py", line 229, in <module>
    train()
  File "train.py", line 125, in train
    scores=fast_rcnn_score)
  File "../libs/box_utils/show_box_in_tensor.py", line 167, in draw_boxes_with_categories
    Tout=[tf.uint8])
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 198, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/ops/gen_script_ops.py", line 38, in _py_func
    name=name)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/yin/anaconda3/envs/py27/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnknownError (see above for traceback): exceptions.KeyError: 2
	 [[Node: draw_boxes_with_categories/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT64, DT_FLOAT], Tout=[DT_UINT8], token="pyfunc_8", _device="/job:localhost/replica:0/task:0/cpu:0"](draw_boxes_with_categories/Squeeze/_2703, fast_rcnn_predict/fast_rcnn_proposals/Gather_6/_2705, fast_rcnn_predict/fast_rcnn_proposals/Gather_8, fast_rcnn_predict/fast_rcnn_proposals/Gather_7/_2707)]]
	 [[Node: draw_boxes_with_categories/Reshape/tensor/_2709 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_4969_draw_boxes_with_categories/Reshape/tensor", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by 610718613** [comment]
请问您现在调好了么？

**Comment by Yinruihao** [comment]
我还没调好，这个代码还是不错的 我这几天要写一个keras版本的出来。

**Comment by yangxue0827** [comment]
@Yinruihao @610718613 https://github.com/DetectionTeamUCAS/Faster-RCNN_Tensorflow

**Comment by gongyilong** [comment]
我和你同样的错误，解决了吗？

**Comment by Jnyle** [comment]
请问解决了吗
