### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by xianyujie** [yangxue0827/FPN_Tensorflow#41]
`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1350, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1329, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: OverflowError: signed integer is less than minimum
	 [[Node: draw_proposals/PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_5", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_losses/Squeeze/_3081, rpn_proposals/cond/Merge/_3157, draw_proposals/strided_slice_1/_3159)]]
	 [[Node: fast_rcnn_loss/Reshape_2/tensor/_3243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3177_fast_rcnn_loss/Reshape_2/tensor", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xjyu/work/FPN_Tensorflow-master/tools/train.py", line 227, in <module>
    train()
  File "/home/xjyu/work/FPN_Tensorflow-master/tools/train.py", line 209, in train
    summary_str = sess.run(summary_op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1344, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1363, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: OverflowError: signed integer is less than minimum
	 [[Node: draw_proposals/PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_5", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_losses/Squeeze/_3081, rpn_proposals/cond/Merge/_3157, draw_proposals/strided_slice_1/_3159)]]
	 [[Node: fast_rcnn_loss/Reshape_2/tensor/_3243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3177_fast_rcnn_loss/Reshape_2/tensor", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'draw_proposals/PyFunc_1', defined at:
  File "/home/xjyu/work/FPN_Tensorflow-master/tools/train.py", line 227, in <module>
    train()
  File "/home/xjyu/work/FPN_Tensorflow-master/tools/train.py", line 88, in train
    text=tf.shape(rpn_proposals_boxes)[0])
  File "/home/xjyu/work/FPN_Tensorflow-master/libs/box_utils/show_box_in_tensor.py", line 63, in draw_box_with_color
    Tout=[tf.uint8])
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 300, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/script_ops.py", line 209, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 93, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3160, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1625, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): OverflowError: signed integer is less than minimum
	 [[Node: draw_proposals/PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_5", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_losses/Squeeze/_3081, rpn_proposals/cond/Merge/_3157, draw_proposals/strided_slice_1/_3159)]]
	 [[Node: fast_rcnn_loss/Reshape_2/tensor/_3243 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_3177_fast_rcnn_loss/Reshape_2/tensor", tensor_type=DT_UINT8, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

**Comment by yangxue0827** [comment]
Sorry, I don't know how to solve it. May be an opencv bug. @xianyujie

**Comment by yangxue0827** [comment]
Recommend improved code: https://github.com/DetectionTeamUCAS/FPN_Tensorflow. @xianyujie
