### ISSUE TITLE
How can i use multi_gpu to train and change the BatchSize?

### ISSUE THREAD

**Issue by heiyuxiaokai** [yangxue0827/FPN_Tensorflow#43]
1.It seems that FPN_Tensorflow doesn't support multi-gpu-train mode.
2.When i change the BatchSize from 1 to 64, i get that error:
Traceback (most recent call last):
File "./tools/train.py", line 229, in
train()
File "./tools/train.py", line 38, in train
text=tf.shape(gtboxes_and_label_batch)[1])
File "./tools/../libs/box_utils/show_box_in_tensor.py", line 59, in draw_box_with_color
img_tensor = tf.squeeze(img_batch, 0)
File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 2630, in squeeze
return gen_array_ops.squeeze(input, axis, name)
File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 7862, in squeeze
"Squeeze", input=input, squeeze_dims=axis, name=name)
File "/home/rf/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
op_def=op_def)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
op_def=op_def)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1734, in init
control_input_ops)
File "/home/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1570, in _create_c_op
raise ValueError(str(e))
ValueError: Can not squeeze dim[0], expected a dimension of 1, got 64 for 'draw_gtboxes/Squeeze' (op: 'Squeeze') with input shapes: [64,?,?,3].

how can i solve these two problem？

**Comment by yangxue0827** [comment]
You need write a multi-gpu training script by yourself if you want to train with multiple gpu Besides, batchsize can only be 1. @heiyuxiaokai

**Comment by heiyuxiaokai** [comment]
Get it, thanks.
In cfgs.py, there are some definitions about learnrate, batchsize and so on. But in config_res101.py, there some similar definitions like batchsize, lr_begin. It seems cfg.py's parameter-definition works. What's the differences?
In cfg.py, I can't find the parameter-definition about learnrate decay. Does it exist？

**Comment by yangxue0827** [comment]
[here](https://github.com/yangxue0827/FPN_Tensorflow/blob/master/tools/train.py#L134) @heiyuxiaokai

**Comment by yangxue0827** [comment]
You only need to convert the data to tfrecord. @heiyuxiaokai
