### ISSUE TITLE
Unknown command line flag 'src_folder'

### ISSUE THREAD

**Issue by 1451595897** [yangxue0827/FPN_Tensorflow#47]
When I run the demo,it shows that absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'src_folder'.How can I deal with this problem?
![image](https://user-images.githubusercontent.com/39090271/49154837-71fcde80-f354-11e8-9994-935be291ff0a.png)

**Comment by yangxue0827** [comment]
example: python demo.py --src_folder=./demo_src --des_folder=./demo_des @1451595897

**Comment by 1451595897** [comment]
你好，我发现我一开始tfrecords生成不正确，我用的的voc2007数据集，我用命令python convert_data_to_tfrecord.py --VOC_dir='home/dell/huanglongfei/FPN_Tensorflow/data/pascal/VOCdevkit/VOCdevkit_train' --save_name='train' --img_format='.jpg' --dataset='pascal'
最后生成的pascal_train.tfrecord文件字节为0，不知道这个问题该怎么解决呢？ @yangxue0827

**Comment by yangxue0827** [comment]
你debug单步调试一下，你这个问题肯定是哪里文件没找到，路径有问题 。 @1451595897

**Comment by lilmangolil** [comment]
> 你好，我发现我一开始tfrecords生成不正确，我用的的voc2007数据集，我用命令python convert_data_to_tfrecord.py --VOC_dir='home/dell/huanglongfei/FPN_Tensorflow/data/pascal/VOCdevkit/VOCdevkit_train' --save_name='train' --img_format='.jpg' --dataset='pascal'
> 最后生成的pascal_train.tfrecord文件字节为0，不知道这个问题该怎么解决呢？ @yangxue0827

应该是路径之类的问题，之前我也遇到过

**Comment by 1451595897** [comment]
你好，不知道你之前是哪里的路径出现问题了，才导致最后生成的tfrecords为0字节的？ @lilmangolil

**Comment by lilmangolil** [comment]
> 你好，不知道你之前是哪里的路径出现问题了，才导致最后生成的tfrecords为0字节的？ @lilmangolil

要把数据库的路径，数据库的名字都对应好，另外libs文件夹下面的cfgs.py也有很多路径要对应上，以及数据库名字。

**Comment by yangxue0827** [comment]
Recommend improved code: https://github.com/DetectionTeamUCAS/FPN_Tensorflow. @1451595897 @lilmangolil

**Comment by ZHUANG-JLU** [comment]
(venv) zhj@zhj-virtual-machine:~/PycharmProjects/study/tensorflow/FPN_Tensorflow-master/tools$ python demo.py --src_folder=./inference_image/sample.tif --des_folder=./output

Called with args:
Namespace(des_folder='./output', det_th=0.7, h_len=600, h_overlap=200, image_ext='.tif', src_folder='./inference_image/sample.tif', w_len=1000, w_overlap=200)
Traceback (most recent call last):
  File "demo.py", line 290, in <module>
    detect_img(file_paths, args.des_folder, args.det_th, args.h_len, args.w_len, args.h_overlap, args.w_overlap, False)
  File "demo.py", line 88, in detect_img
    spatial_squeeze=False)
  File "../libs/networks/network_factory.py", line 63, in get_network_byname
    with slim.arg_scope(resnet_v1.resnet_arg_scope(weight_decay=FLAGS.weight_decay)):
  File "/home/zhj/PycharmProjects/study/venv/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/zhj/PycharmProjects/study/venv/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 632, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'src_folder'
请问下如何解决 @yangxue0827 @1451595897

**Comment by yangxue0827** [comment]
src_folder是文件夹目录，不是单个图片的路径 @zhuanghongjie

**Comment by ZHUANG-JLU** [comment]
(venv) zhj@zhj-virtual-machine:~/PycharmProjects/study/tensorflow/FPN_Tensorflow-master/tools$ python demo.py --src_folder=./input --des_folder=./output

Called with args:
Namespace(des_folder='./output', det_th=0.7, h_len=600, h_overlap=200, image_ext='.tif', src_folder='./input', w_len=1000, w_overlap=200)
Traceback (most recent call last):
  File "demo.py", line 290, in <module>
    detect_img(file_paths, args.des_folder, args.det_th, args.h_len, args.w_len, args.h_overlap, args.w_overlap, False)
  File "demo.py", line 88, in detect_img
    spatial_squeeze=False)
  File "../libs/networks/network_factory.py", line 63, in get_network_byname
    with slim.arg_scope(resnet_v1.resnet_arg_scope(weight_decay=FLAGS.weight_decay)):
  File "/home/zhj/PycharmProjects/study/venv/lib/python3.5/site-packages/tensorflow/python/platform/flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "/home/zhj/PycharmProjects/study/venv/lib/python3.5/site-packages/absl/flags/_flagvalues.py", line 632, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'src_folder'

还是不行 @yangxue0827
