### ISSUE TITLE
训练一段时间报错

### ISSUE THREAD

**Issue by tsstjj** [yangxue0827/FPN_Tensorflow#63]
楼主您好，我训练到大概10000多部步，然后报错
`2019-08-24 14:27:28.661732: W tensorflow/core/framework/op_kernel.cc:1306] Invalid argument: TypeError: Required argument 'rec' (pos 2) not found
Traceback (most recent call last):
File "/home/chenglong/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 157, in __call__
    ret = func(*args)

  File "/media/chenglong/huang/project/detection/FPN_Tensorflow/libs/box_utils/show_box_in_tensor.py", line 45, in draw_box_cv
    thickness=2)

TypeError: Required argument 'rec' (pos 2) not found

[[Node: draw_proposals/PyFunc = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_INT32], Tout=[DT_UINT8], token="pyfunc_4", _device="/job:localhost/replica:0/task:0/device:CPU:0"](rpn_losses/Squeeze/_1121, draw_proposals/GatherV2/_1189, draw_proposals/strided_slice/_1191)]]
	 [[Node: draw_proposals/Reshape_1/tensor/_1193 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GP
`

**Comment by ZhengHeZhe** [comment]
请问你的问题解决了吗  我也遇到了这样的问题
