### ISSUE TITLE
OverflowError: Python int too large to convert to C longOverflowError: Python int too large to convert to C long

### ISSUE THREAD

**Issue by leiyaohui** [yangxue0827/FPN_Tensorflow#68]
UnknownError (see above for traceback): OverflowError: Python int too large to convert to C long
Traceback (most recent call last):

  File "D:\Anaconda\lib\site-packages\tensorflow\python\ops\script_ops.py", line 157, in __call__
    ret = func(*args)

  File "F:\FPN\FPN_Tensorflow-master\libs\box_utils\show_box_in_tensor.py", line 45, in draw_box_cv
    thickness=2)

OverflowError: Python int too large to convert to C long
您好，我遇到这种问题，请问该怎么解决呢？

**Comment by yellowsmallblue** [comment]
您好，我也出现了这个问题，请问您解决了么
