### ISSUE TITLE
batchsize问题

### ISSUE THREAD

**Issue by MsRabbits** [yangxue0827/FPN_Tensorflow#70]
作者您好  我按照您的代码自己复现了一遍 想请问如果我自己改写的话 batchsize想增加的话 是要从什么角度更改您的代码呢 谢谢您

**Comment by yangxue0827** [comment]
这个repo的效果不好，建议用这个FPN：https://github.com/DetectionTeamUCAS/FPN_Tensorflow

要改成多bs的话，数据的读取，roi的assign什么的，正负样本的采样等，很多地方都要修改。

**Comment by MsRabbits** [comment]
> 这个repo的效果不好，建议用这个FPN：https://github.com/DetectionTeamUCAS/FPN_Tensorflow
> 
> 要改成多bs的话，数据的读取，roi的assign什么的，正负样本的采样等，很多地方都要修改。

好的谢谢您的回复！我看您新发的这个版本的好像也是batchsize设置为1的，因为我的数据集有三万张图，我昨天试着跑了一天发现loss一直震荡，这个和batchsize太小是不是有关系呢，还有请请教您三万张训练集的话您这个代码我应该跑多少代才会有效果呢？

**Comment by yangxue0827** [comment]
20个epoch左右吧，一般第一次学习率下降之后的那个epoch效果趋于稳定。

**Comment by MsRabbits** [comment]
> 20个epoch左右吧，一般第一次学习率下降之后的那个epoch效果趋于稳定。
好的 谢谢您回复。再想请教一下测试模型的话 是直接运行eval.py就可以了吗

**Comment by MsRabbits** [comment]
我在运行eval.py的时候报了下面这个错误，请问这个应该是什么原因呢？
Traceback (most recent call last):
  File "E:/Tree/sar_ship_detection_batch/FPN_TensorFlow/tools/eval.py", line 323, in <module>
    eval_dict_convert(args)
  File "E:/Tree/sar_ship_detection_batch/FPN_TensorFlow/tools/eval.py", line 45, in eval_dict_convert
    spatial_squeeze=False)
  File "E:/Tree/sar_ship_detection_batch/FPN_TensorFlow/tools\..\data\io\../..\libs\networks\network_factory.py", line 49, in get_network_byname
    with slim.arg_scope(resnet_v1.resnet_arg_scope(weight_decay=FLAGS.weight_decay)):
  File "E:\anaconda\anaconda\envs\tensorflow\lib\site-packages\tensorflow\python\platform\flags.py", line 84, in __getattr__
    wrapped(_sys.argv)
  File "E:\anaconda\anaconda\envs\tensorflow\lib\site-packages\absl\flags\_flagvalues.py", line 633, in __call__
    name, value, suggestions=suggestions)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'weights'. Did you mean: weight_decay ?
